### PR TITLE
Import Toolbox

### PR DESCRIPTION
**Pull request by IanSaucy**
This PR is for the import tools to transform standard Twitter JSON files into a CSV or pickle format that is used by later steps in the pipeline. It supports output to both CSVs and or PKL files. In addition, it supports searching the entire specified folder, including sub folders for source files. Lastly, it will transparently decompress tar files to access the contents.

### CODE REVIEW

**Comment by IanSaucy** [comment]
As a point of clarification, this PR is not ready to merge. It's just been opened to review the code and get someone else to test it!

**Comment by LaChapeliere** [comment]
What's the package you're using to type the function parameters?

fileHandler.py -> Pretty straightforward :) You're missing the function description in the doc

importDriver.py -> I'd specify the unit of --max-in-memory. Maybe I missed something in the doc of argparse, but why are you sometimes using --arg_name and sometimes -arg_name? I thought the single dash was for shorthand and the double one for full arg name? Otherwise looking good, I think we have all the necessary options :)

transform.py -> I don't understand why you are cutting things into chunks twice (in _process_files_ lines 55-58 and in _write_tweets_by_chunk_ lines 88-91). Is it because _process_tar_file_ calls _write_tweets_by_chunk_ directly and therefore does not cut things into chunks before? In that case, maybe it would be better to call _process_files_ on the uncompressed file in _process_tar_file_?
In _parse_tweet_ I'd add some JSON validation to check that the necessary fields exist. If I'm not mistaken right now the code is not dealing with cases with a valid JSON is loaded but contains stuff that is not tweets. Then you can add those errors to failure_count.
Line 142, the multiple negations make it a bit difficult to wrap one's head around.
Looks like you're pickling the list(list()) directly, would it be possible to pickle it in pandas DataFrame instead? So that it's coherent over the entire pipeline. If not we'll change the interface specs.

Great work making it work with all those formats, especially the pickled ones!!
What about creating an enhancement issue later to add entry points for other formats? I'm thinking CSV in particular, people might already have dumped their data in CSV format. Not necessary for a first version, but with an issue open we'll keep it in mind.

**Comment by LaChapeliere** [comment]
Also, you are saving everything to a single file, right (or two if CSV+pickled mode)? So for the rest of the pipeline, should we plan that everything is in one huge file rather than a folder of memory-loadable files?

**Comment by IanSaucy** [comment]
In regards to the last comment, yes, it's saving it into one giant file. I would like to have it split into chunks but that will need to be a future enhancement. So ideally the rest of the pipeline can handle multiple files -- especially since we give the user the option of providing their own pre-formatted CSV data.

**Comment by LaChapeliere** [comment]
Okay, I'll adapt our code and take over the file-reading/saving from Kelly on the preprocessing then, I doubt she'll want to tackle partial file-reading :)

**Comment by LaChapeliere** [comment]
I noticed in transform.py, line 168, that you are saving the tweet info in order id, timestamp, text.
Can you change it to id, text, timestamp please so it fits the interface specs :) ?

And we also need the header there, to check that the file is valid. (See https://trello.com/c/vqqm4fOy/23-define-specs-for-interfaces-between-modules)

**Comment by IanSaucy** [comment]
Most of the comments above have been addressed, mainly the pickle file support has been removed. We did this because there is no way to open only part of a pickle file, as this library is built to handle very large datasets this would make it impossible to use due to memory constraints. 

In addition, doc comments have been added. Lastly, the double chunking mentioned in `process_files` has been resolved as well. Good catch @LaChapeliere

**Comment by IanSaucy** [comment]
@LaChapeliere You think this is good to move into our dev branch?

**Comment by IanSaucy** [comment]
Test deployed to:
https://test.pypi.org/project/CRANE-Toolbox/

**Comment by IanSaucy** [comment]
@LaChapeliere Good to merge?

**Comment by LaChapeliere** [comment]
I'm pushing commits with updates to the doc, no deep modifications, just making sure everything is formatted the same.
Also a commit to refactor the retweets detections, to remove the triple negation that was doing my head in ^^.

**Comment by LaChapeliere** [comment]
I'll create issues for the JSON validation task and choosing whether to add a header to the CSV file, that way we can merge and improve later :)

**Review by LaChapeliere — APPROVED** [review]
Let's go :)

**Pull request merged**
