### PR TITLE
Deal with ordinal numbers in preprocessing functions

### PR DESCRIPTION
**Pull request by ccatterina**
- Function `replace_numbers()` now handles also ordinal numbers.
- Add tests for `replace_numbers()` function.

Fixes #43

### CODE REVIEW

**Review by LaChapeliere — CHANGES_REQUESTED** [review]
Works great on my side!
Could you please add a couple of tests for "st" and "rd" ordinal numbers, including one that's more than one digit, since ordinal numbers are more bothersome about that than cardinal ones? That way the test will be solid :)

**Comment by ccatterina** [comment]
> Could you please add a couple of tests for "st" and "rd" ordinal numbers, including one that's more than one digit, since ordinal numbers are more bothersome about that than cardinal ones? That way the test will be solid :)

Sure, I'm on it!

**Comment by ccatterina** [comment]
Updated, feel free to tell me if I missed something.

**Comment by LaChapeliere** [comment]
It is not letting me review, I believe you have to say that you have done the requested changes?

**Review by LaChapeliere — APPROVED** [review]
Great work and through testing, thanks! You even improved tests for cardinal numbers <3
I love your implementation, it's much more efficient than what was proposed in num2words doc.

**Comment by ccatterina** [comment]
Thank you! :grinning:

**Pull request merged**
