### PR TITLE
Fix importTools import issue

### PR DESCRIPTION
**Pull request by IanSaucy**
This PR fixes a bug that caused a fatal error in the importTools package. The package version has also been updated since these changes have been deployed to testpypi

### CODE REVIEW

**Comment by LaChapeliere** [comment]
Could you also fix the typo in the CLI args that Kelly noticed? --output_folder -> --output-folder

**Comment by IanSaucy** [comment]
Updated

**Comment by IanSaucy** [comment]
@LaChapeliere Ready for re-review

**Review by LaChapeliere — APPROVED** [review]
Tested on Ian's server (Linux), on one day of data from Gianluca

**Pull request merged**
